anypoint.platform.analytics_base_uri: "https://analytics-ingest.anypoint.mulesoft.com/"
anypoint.platform.client_id: "76d2db87d9e54788ac53a25d3922fe26"
anypoint.platform.client_secret: "41e23E342a4c4CC2aE998a3DE452c680"
anypoint.platform.base_uri: "https://anypoint.mulesoft.com/"